//! WireGuard through `wg-quick`, and through `wireguard.exe` on Windows.
//!
//! Three things shape this module. `wg-quick up` accepts a path, so the configs
//! controlcenter generates can live in its own config directory and nothing ever
//! has to be written into root-owned `/etc/wireguard`. `wg show` needs
//! CAP_NET_ADMIN, so the five-second poll uses `ip` instead — an interface named
//! after a profile existing is exactly what "that profile is up" means. And
//! Windows has no `wg-quick` at all: there the same config is handed to
//! `wireguard.exe /installtunnelservice`, which registers a service that owns
//! the tunnel, and the adapter it creates is again named after the file. So the
//! rule that reads the state — an interface named after the profile is that
//! profile being up — is the same one on both, which is why the poll below is
//! not two polls.

use super::{privileged, ProviderId, VpnMsg, VpnProfile, VpnStatus};
#[cfg(not(windows))]
use crate::platform::which_bin;
use crate::types::WireguardProfile;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::mpsc::Sender;
use std::thread;

const ME: ProviderId = ProviderId::Wireguard;

/// Linux caps interface names at IFNAMSIZ - 1.
const MAX_IFNAME: usize = 15;

impl WireguardProfile {
    /// The interface wg-quick will create, which is the config's basename.
    pub fn interface(&self) -> String {
        if self.config_path.is_empty() {
            return self.name.clone();
        }
        Path::new(&self.config_path)
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| self.name.clone())
    }

    /// Whether the config is someone else's to maintain.
    pub fn external(&self) -> bool {
        !self.config_path.is_empty()
    }

    pub fn summary(&self) -> String {
        if self.external() {
            return self.config_path.clone();
        }
        if self.endpoint.is_empty() {
            String::new()
        } else {
            self.endpoint.clone()
        }
    }
}

/// wg-quick names the interface after the file, so the profile name has to be a
/// name the kernel will accept.
pub fn validate_ifname(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("name is required".into());
    }
    if name.len() > MAX_IFNAME {
        return Err(format!(
            "'{name}' is {} characters; an interface name may be at most {MAX_IFNAME}",
            name.len()
        ));
    }
    if name == "." || name == ".." {
        return Err("'.' and '..' are not interface names".into());
    }
    if let Some(bad) = name
        .chars()
        .find(|c| !(c.is_ascii_alphanumeric() || "_=+.-".contains(*c)))
    {
        return Err(format!("'{bad}' is not allowed in an interface name"));
    }
    Ok(())
}

/// What a profile has to have before wg-quick can do anything with it.
pub fn validate(p: &WireguardProfile) -> Result<(), String> {
    validate_ifname(&p.name)?;
    if p.external() {
        return Ok(());
    }
    if p.private_key.is_empty() {
        return Err("a private key is required — press g to generate one".into());
    }
    if p.address.is_empty() {
        return Err("address is required, e.g. 10.0.0.2/24".into());
    }
    if p.peer_public_key.is_empty() {
        return Err("the peer's public key is required".into());
    }
    if p.endpoint.is_empty() {
        return Err("endpoint is required, e.g. vpn.example.com:51820".into());
    }
    // A wg-quick concern only: it shells out to one of these to install the
    // DNS server. The Windows service does it itself and needs neither.
    #[cfg(not(windows))]
    if !p.dns.is_empty() && which_bin("resolvconf").is_none() && which_bin("resolvectl").is_none() {
        return Err(
            "DNS is set but neither resolvconf nor resolvectl is on PATH; wg-quick will fail"
                .into(),
        );
    }
    Ok(())
}

/// The `.conf` handed to wg-quick. The stored profile is the source of truth, so
/// this is regenerated on every save rather than parsed back.
pub fn render_conf(p: &WireguardProfile) -> String {
    let mut s = String::from("# generated by controlcenter — edits here are overwritten\n\n");
    s.push_str("[Interface]\n");
    s.push_str(&format!("PrivateKey = {}\n", p.private_key));
    if !p.address.is_empty() {
        s.push_str(&format!("Address = {}\n", p.address));
    }
    if !p.dns.is_empty() {
        s.push_str(&format!("DNS = {}\n", p.dns));
    }
    if p.listen_port != 0 {
        s.push_str(&format!("ListenPort = {}\n", p.listen_port));
    }
    if p.mtu != 0 {
        s.push_str(&format!("MTU = {}\n", p.mtu));
    }
    s.push_str("\n[Peer]\n");
    s.push_str(&format!("PublicKey = {}\n", p.peer_public_key));
    if !p.preshared_key.is_empty() {
        s.push_str(&format!("PresharedKey = {}\n", p.preshared_key));
    }
    s.push_str(&format!("Endpoint = {}\n", p.endpoint));
    s.push_str(&format!("AllowedIPs = {}\n", p.allowed_ips));
    if p.persistent_keepalive != 0 {
        s.push_str(&format!(
            "PersistentKeepalive = {}\n",
            p.persistent_keepalive
        ));
    }
    s
}

pub fn conf_path(p: &WireguardProfile, dir: &Path) -> PathBuf {
    if p.external() {
        PathBuf::from(&p.config_path)
    } else {
        dir.join(format!("{}.conf", p.name))
    }
}

/// Materialise the config wg-quick will read. External configs are left alone.
pub fn write_conf(p: &WireguardProfile, dir: &Path) -> Result<PathBuf, String> {
    let path = conf_path(p, dir);
    if p.external() {
        if !path.exists() {
            return Err(format!("{} does not exist", path.display()));
        }
        return Ok(path);
    }
    std::fs::create_dir_all(dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;
    std::fs::write(&path, render_conf(p))
        .map_err(|e| format!("writing {}: {e}", path.display()))?;
    super::restrict_file(&path)?;
    Ok(path)
}

pub fn remove_conf(p: &WireguardProfile, dir: &Path) {
    if !p.external() {
        let _ = std::fs::remove_file(conf_path(p, dir));
    }
}

fn wg(args: &[&str], stdin: Option<&str>) -> Result<String, String> {
    use std::io::Write;
    use std::process::Stdio;
    let mut cmd = Command::new(crate::platform::program("wg"));
    #[cfg(windows)]
    {
        crate::platform::hidden(&mut cmd);
    }
    cmd.args(args).stdout(Stdio::piped()).stderr(Stdio::piped());
    if stdin.is_some() {
        cmd.stdin(Stdio::piped());
    }
    let mut child = cmd.spawn().map_err(|e| format!("running wg: {e}"))?;
    if let (Some(text), Some(mut pipe)) = (stdin, child.stdin.take()) {
        let _ = pipe.write_all(text.as_bytes());
    }
    let out = child.wait_with_output().map_err(|e| format!("wg: {e}"))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
    } else {
        let e = String::from_utf8_lossy(&out.stderr).trim().to_string();
        Err(if e.is_empty() {
            format!("wg {} failed", args.join(" "))
        } else {
            e
        })
    }
}

/// A fresh private key and the public key that goes with it. Both unprivileged.
pub fn generate_keypair() -> Result<(String, String), String> {
    let private = wg(&["genkey"], None)?;
    let public = public_key(&private)?;
    Ok((private, public))
}

pub fn public_key(private: &str) -> Result<String, String> {
    wg(&["pubkey"], Some(&format!("{private}\n")))
}

// ---------------------------------------------------------------------------
// Reading the live state
//
// Three questions — which interfaces exist, what address one has, how much has
// gone through it — asked of `ip` on Unix and of PowerShell on Windows. All six
// answers are unprivileged: a status poll never escalates.
// ---------------------------------------------------------------------------

/// The wireguard interfaces that currently exist, which is the list of profiles
/// that are up.
#[cfg(not(windows))]
fn interfaces_up() -> Result<Vec<String>, String> {
    ip(&["-o", "link", "show", "type", "wireguard"]).map(|out| parse_interfaces(&out))
}

/// Names of the wireguard interfaces that currently exist. `ip` is unprivileged,
/// which is the whole reason the poll uses it instead of `wg show`.
#[cfg(any(not(windows), test))]
fn parse_interfaces(raw: &str) -> Vec<String> {
    raw.lines()
        .filter_map(|line| {
            let after_index = line.split_once(':')?.1;
            let name = after_index.split(':').next()?.trim();
            // `ip` writes "wg0@if7" for stacked links; the device is the left half.
            let name = name.split('@').next()?.trim();
            (!name.is_empty()).then(|| name.to_string())
        })
        .collect()
}

#[cfg(not(windows))]
fn ip(args: &[&str]) -> Result<String, String> {
    let out = Command::new("ip")
        .args(args)
        .output()
        .map_err(|e| format!("running ip: {e}"))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
    }
}

/// The address the interface actually got.
#[cfg(not(windows))]
fn addresses(iface: &str) -> Vec<String> {
    ip(&["-o", "addr", "show", "dev", iface])
        .map(|out| parse_addresses(&out))
        .unwrap_or_default()
}

/// From `ip -o addr show dev <iface>`.
#[cfg(any(not(windows), test))]
fn parse_addresses(raw: &str) -> Vec<String> {
    raw.lines()
        .filter_map(|line| {
            let mut it = line.split_whitespace();
            let family = it.by_ref().nth(2)?;
            if family != "inet" && family != "inet6" {
                return None;
            }
            it.next().map(str::to_string)
        })
        .collect()
}

/// Bytes in and out, the closest thing to `wg show` transfer stats without root.
#[cfg(not(windows))]
fn counters(iface: &str) -> Option<(u64, u64)> {
    parse_counters(&ip(&["-s", "link", "show", "dev", iface]).ok()?)
}

/// From `ip -s link show dev <iface>`, which is also unprivileged.
#[cfg(any(not(windows), test))]
fn parse_counters(raw: &str) -> Option<(u64, u64)> {
    let lines: Vec<&str> = raw.lines().map(str::trim).collect();
    let mut rx = None;
    let mut tx = None;
    for (i, line) in lines.iter().enumerate() {
        let first = |s: &str| s.split_whitespace().next()?.parse::<u64>().ok();
        if line.starts_with("RX:") {
            rx = lines.get(i + 1).and_then(|l| first(l));
        } else if line.starts_with("TX:") {
            tx = lines.get(i + 1).and_then(|l| first(l));
        }
    }
    Some((rx?, tx?))
}

// ---------------------------------------------------------------------------
// The same three questions, asked of Windows
// ---------------------------------------------------------------------------

/// A name going into a PowerShell single-quoted string. The interface names
/// controlcenter generates cannot contain a quote, but one taken from the stem
/// of a config file the user pointed at can.
#[cfg(any(windows, test))]
fn ps_quote(name: &str) -> String {
    name.replace('\'', "''")
}

/// The tunnels `wireguard.exe` currently has installed.
///
/// Asked of the services rather than the adapters: `/installtunnelservice`
/// registers `WireGuardTunnel$<name>`, so the service list is the state
/// exactly, including a tunnel whose adapter has not appeared yet. Reading it
/// needs nothing beyond being logged in.
#[cfg(windows)]
fn interfaces_up() -> Result<Vec<String>, String> {
    crate::platform::powershell(
        "Get-Service -Name 'WireGuardTunnel$*' -ErrorAction SilentlyContinue | Select-Object Name,Status | ConvertTo-Csv -NoTypeInformation",
    )
    .map(|out| parse_services(&out))
}

/// The profile names out of `Get-Service`'s rows: `WireGuardTunnel$home` is the
/// tunnel `home`. A service that is registered but not running is not up.
#[cfg(any(windows, test))]
fn parse_services(raw: &str) -> Vec<String> {
    use crate::platform::{csv_field, parse_csv};
    parse_csv(raw)
        .iter()
        .filter(|row| csv_field(row, "Status") == Some("Running"))
        .filter_map(|row| {
            let name = csv_field(row, "Name")?;
            let (_, tunnel) = name.split_once('$')?;
            (!tunnel.is_empty()).then(|| tunnel.to_string())
        })
        .collect()
}

#[cfg(windows)]
fn addresses(iface: &str) -> Vec<String> {
    let script = format!(
        "Get-NetIPAddress -InterfaceAlias '{}' -ErrorAction SilentlyContinue | Select-Object IPAddress,PrefixLength | ConvertTo-Csv -NoTypeInformation",
        ps_quote(iface)
    );
    crate::platform::powershell(&script)
        .map(|out| parse_windows_addresses(&out))
        .unwrap_or_default()
}

#[cfg(any(windows, test))]
fn parse_windows_addresses(raw: &str) -> Vec<String> {
    use crate::platform::{csv_field, parse_csv};
    parse_csv(raw)
        .iter()
        .filter_map(|row| {
            let addr = csv_field(row, "IPAddress")?;
            Some(match csv_field(row, "PrefixLength") {
                Some(prefix) => format!("{addr}/{prefix}"),
                None => addr.to_string(),
            })
        })
        .collect()
}

#[cfg(windows)]
fn counters(iface: &str) -> Option<(u64, u64)> {
    let script = format!(
        "Get-NetAdapterStatistics -Name '{}' -ErrorAction SilentlyContinue | Select-Object ReceivedBytes,SentBytes | ConvertTo-Csv -NoTypeInformation",
        ps_quote(iface)
    );
    parse_windows_counters(&crate::platform::powershell(&script).ok()?)
}

#[cfg(any(windows, test))]
fn parse_windows_counters(raw: &str) -> Option<(u64, u64)> {
    use crate::platform::{csv_field, parse_csv};
    let rows = parse_csv(raw);
    let row = rows.first()?;
    Some((
        csv_field(row, "ReceivedBytes")?.parse().ok()?,
        csv_field(row, "SentBytes")?.parse().ok()?,
    ))
}

fn status_for(profile: &WireguardProfile, iface: &str) -> VpnStatus {
    let mut fields = vec![("Interface".to_string(), iface.to_string())];
    let addrs = addresses(iface);
    if !addrs.is_empty() {
        fields.push(("Address".into(), addrs.join(", ")));
    }
    if !profile.endpoint.is_empty() {
        fields.push(("Endpoint".into(), profile.endpoint.clone()));
    }
    if !profile.allowed_ips.is_empty() {
        fields.push(("Allowed IPs".into(), profile.allowed_ips.clone()));
    }
    if !profile.dns.is_empty() {
        fields.push(("DNS".into(), profile.dns.clone()));
    }
    if profile.external() {
        fields.push(("Config".into(), profile.config_path.clone()));
    }
    if let Some((rx, tx)) = counters(iface) {
        fields.push((
            "Transfer".into(),
            format!(
                "{} received, {} sent",
                crate::ui::human_bytes(rx),
                crate::ui::human_bytes(tx)
            ),
        ));
    }
    VpnStatus {
        connected: true,
        active_profile: Some(profile.name.clone()),
        fields,
        error: None,
    }
}

pub fn refresh(tx: Sender<VpnMsg>, stored: Vec<WireguardProfile>) {
    thread::spawn(move || {
        let up = match interfaces_up() {
            Ok(names) => names,
            Err(e) => {
                let _ = tx.send(VpnMsg::Refreshed {
                    provider: ME,
                    profiles: Ok(Vec::new()),
                    status: VpnStatus::failed(format!("could not list interfaces: {e}")),
                });
                return;
            }
        };

        let profiles: Vec<VpnProfile> = stored
            .iter()
            .map(|p| VpnProfile {
                active: up.contains(&p.interface()),
                name: p.name.clone(),
                detail: p.summary(),
                foreign: None,
            })
            .collect();

        // Only an interface belonging to one of our profiles counts as
        // connected. Other wireguard interfaces belong to something else —
        // netbird runs one of its own — so they are reported, not claimed.
        let live = stored.iter().find(|p| up.contains(&p.interface()));
        let mut status = match live {
            Some(p) => status_for(p, &p.interface()),
            None => VpnStatus::default(),
        };
        let strangers: Vec<&String> = up
            .iter()
            .filter(|iface| !stored.iter().any(|p| &p.interface() == *iface))
            .collect();
        if !strangers.is_empty() {
            let names: Vec<&str> = strangers.iter().map(|s| s.as_str()).collect();
            status.fields.push((
                "Other interfaces".into(),
                format!("{} (not controlcenter's)", names.join(", ")),
            ));
        }

        let _ = tx.send(VpnMsg::Refreshed {
            provider: ME,
            profiles: Ok(profiles),
            status,
        });
    });
}

fn action(tx: Sender<VpnMsg>, desc: String, argv: Vec<String>, stored: Vec<WireguardProfile>) {
    thread::spawn(move || {
        let error = privileged::run(&argv).err();
        let _ = tx.send(VpnMsg::ActionDone {
            provider: ME,
            desc,
            error,
        });
        refresh(tx, stored);
    });
}

/// Bring a profile up. Returns the command line it launched, for the log; the
/// config it needs is written first, and a failure there means nothing ran.
pub fn connect(
    tx: Sender<VpnMsg>,
    profile: WireguardProfile,
    dir: &Path,
    stored: Vec<WireguardProfile>,
) -> Vec<String> {
    let desc = format!("bringing up '{}'", profile.name);
    let path = match write_conf(&profile, dir) {
        Ok(p) => p,
        Err(e) => {
            let _ = tx.send(VpnMsg::ActionDone {
                provider: ME,
                desc,
                error: Some(e),
            });
            return Vec::new();
        }
    };
    let argv = up_argv(&path);
    let ran = vec![as_root(&argv)];
    action(tx, desc, argv, stored);
    ran
}

pub fn disconnect(
    tx: Sender<VpnMsg>,
    profile: WireguardProfile,
    dir: &Path,
    stored: Vec<WireguardProfile>,
) -> Vec<String> {
    // `wg-quick down` also accepts a bare interface name, which is what we want
    // when the config was never written or has since been deleted.
    let path = conf_path(&profile, dir);
    let argv = down_argv(&path, &profile.interface());
    let ran = vec![as_root(&argv)];
    action(tx, format!("taking down '{}'", profile.name), argv, stored);
    ran
}

/// Bringing the interface up, per client.
///
/// `wg-quick up <path>` and `wireguard /installtunnelservice <path>` are the
/// same act said twice: both read the config, create the interface named after
/// it, and own it until they are told otherwise.
#[cfg(not(windows))]
pub fn up_argv(conf: &Path) -> Vec<String> {
    vec![
        "wg-quick".to_string(),
        "up".to_string(),
        conf.to_string_lossy().into_owned(),
    ]
}

#[cfg(windows)]
pub fn up_argv(conf: &Path) -> Vec<String> {
    vec![
        "wireguard".to_string(),
        "/installtunnelservice".to_string(),
        conf.to_string_lossy().into_owned(),
    ]
}

/// And taking it down again.
///
/// `wg-quick down` also accepts a bare interface name, which is what we want
/// when the config was never written or has since been deleted. Windows only
/// ever takes the name — the service is registered under it, and the file it
/// was installed from is beside the point by then.
#[cfg(not(windows))]
pub fn down_argv(conf: &Path, interface: &str) -> Vec<String> {
    let target = if conf.exists() {
        conf.to_string_lossy().into_owned()
    } else {
        interface.to_string()
    };
    vec!["wg-quick".to_string(), "down".to_string(), target]
}

#[cfg(windows)]
pub fn down_argv(_conf: &Path, interface: &str) -> Vec<String> {
    vec![
        "wireguard".to_string(),
        "/uninstalltunnelservice".to_string(),
        interface.to_string(),
    ]
}

/// How the log writes a command that went through the escalation helper.
fn as_root(argv: &[String]) -> String {
    format!("{} (as root)", argv.join(" "))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn profile() -> WireguardProfile {
        WireguardProfile {
            name: "home".into(),
            private_key: "cHJpdmF0ZQ==".into(),
            address: "10.0.0.2/24".into(),
            peer_public_key: "cHVibGlj".into(),
            endpoint: "vpn.example.com:51820".into(),
            allowed_ips: "0.0.0.0/0, ::/0".into(),
            ..Default::default()
        }
    }

    #[test]
    fn interface_names_longer_than_the_kernel_allows_are_refused() {
        assert!(validate_ifname("home").is_ok());
        assert!(validate_ifname("wg-office-eu-1").is_ok());
        assert!(validate_ifname("a-sixteen-char-x").is_err());
        assert!(validate_ifname("has space").is_err());
        assert!(validate_ifname("").is_err());
    }

    #[test]
    fn a_rendered_config_omits_the_optional_keys_it_has_no_value_for() {
        let conf = render_conf(&profile());
        assert!(conf.contains("PrivateKey = cHJpdmF0ZQ=="));
        assert!(conf.contains("Address = 10.0.0.2/24"));
        assert!(conf.contains("Endpoint = vpn.example.com:51820"));
        assert!(conf.contains("AllowedIPs = 0.0.0.0/0, ::/0"));
        assert!(!conf.contains("DNS"));
        assert!(!conf.contains("MTU"));
        assert!(!conf.contains("PersistentKeepalive"));
    }

    #[test]
    fn optional_values_appear_once_they_are_set() {
        let p = WireguardProfile {
            dns: "10.0.0.1".into(),
            mtu: 1380,
            persistent_keepalive: 25,
            listen_port: 51820,
            preshared_key: "cHNr".into(),
            ..profile()
        };
        let conf = render_conf(&p);
        assert!(conf.contains("DNS = 10.0.0.1"));
        assert!(conf.contains("MTU = 1380"));
        assert!(conf.contains("ListenPort = 51820"));
        assert!(conf.contains("PresharedKey = cHNr"));
        assert!(conf.contains("PersistentKeepalive = 25"));
    }

    #[test]
    fn an_external_config_supplies_the_interface_name_and_needs_no_other_field() {
        let p = WireguardProfile {
            name: "office".into(),
            config_path: "/etc/wireguard/wg7.conf".into(),
            ..Default::default()
        };
        assert_eq!(p.interface(), "wg7");
        assert!(validate(&p).is_ok());
    }

    #[test]
    fn a_generated_profile_must_carry_everything_wg_quick_needs() {
        assert!(validate(&profile()).is_ok());
        let no_key = WireguardProfile {
            private_key: String::new(),
            ..profile()
        };
        assert!(validate(&no_key).unwrap_err().contains("private key"));
        let no_endpoint = WireguardProfile {
            endpoint: String::new(),
            ..profile()
        };
        assert!(validate(&no_endpoint).unwrap_err().contains("endpoint"));
    }

    #[test]
    fn live_interfaces_are_read_out_of_ip_link_output() {
        let raw = "5: home: <POINTOPOINT,NOARP,UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\\    link/none \n6: wg0@if3: <POINTOPOINT,NOARP,UP> mtu 1420 qdisc noqueue state UNKNOWN\\    link/none \n";
        assert_eq!(parse_interfaces(raw), vec!["home", "wg0"]);
        assert!(parse_interfaces("").is_empty());
    }

    #[test]
    fn addresses_are_read_out_of_ip_addr_output() {
        let raw = "5: home    inet 10.0.0.2/24 scope global home\\       valid_lft forever\n5: home    inet6 fd00::2/128 scope global \\       valid_lft forever\n";
        assert_eq!(parse_addresses(raw), vec!["10.0.0.2/24", "fd00::2/128"]);
    }

    #[test]
    fn an_interface_that_is_not_ours_does_not_count_as_connected() {
        // netbird runs its own kernel wireguard interface; seeing it must not
        // make the wireguard client look connected.
        let stored = [profile()];
        let up = ["wt0".to_string()];
        let live = stored.iter().find(|p| up.contains(&p.interface()));
        assert!(live.is_none());
    }

    #[test]
    fn transfer_counters_are_read_out_of_ip_s_link_output() {
        let raw = "5: home: <POINTOPOINT,NOARP,UP> mtu 1420\n    link/none\n    RX: bytes  packets  errors  dropped  missed   mcast\n    1048576    900      0       0        0        0\n    TX: bytes  packets  errors  dropped  carrier collsns\n    2097152    1200     0       0        0       0\n";
        assert_eq!(parse_counters(raw), Some((1048576, 2097152)));
        assert_eq!(parse_counters("nothing useful"), None);
    }

    // The Windows readers are string parsing, so they are tested here rather
    // than only on the system they run on.

    #[test]
    fn windows_tunnel_services_name_the_profiles_that_are_up() {
        let raw = "\"Name\",\"Status\"\r\n\"WireGuardTunnel$home\",\"Running\"\r\n\"WireGuardTunnel$office\",\"Stopped\"\r\n";
        assert_eq!(parse_services(raw), vec!["home"]);
        assert!(parse_services("").is_empty());
    }

    #[test]
    fn windows_addresses_read_the_way_the_rest_of_the_program_wants_them() {
        let raw = "\"IPAddress\",\"PrefixLength\"\r\n\"10.0.0.2\",\"24\"\r\n\"fd00::2\",\"128\"\r\n";
        assert_eq!(parse_windows_addresses(raw), vec!["10.0.0.2/24", "fd00::2/128"]);
    }

    #[test]
    fn windows_transfer_counters_are_read_out_of_the_adapter_statistics() {
        let raw = "\"ReceivedBytes\",\"SentBytes\"\r\n\"1048576\",\"2097152\"\r\n";
        assert_eq!(parse_windows_counters(raw), Some((1048576, 2097152)));
        assert_eq!(parse_windows_counters("nothing useful"), None);
    }

    #[test]
    fn an_interface_name_cannot_close_the_quote_it_is_passed_in() {
        assert_eq!(ps_quote("wg0"), "wg0");
        assert_eq!(ps_quote("it's"), "it''s");
    }

    #[test]
    fn bringing_a_profile_up_names_the_config_and_taking_it_down_names_the_interface() {
        let conf = Path::new("/tmp/controlcenter-wg-does-not-exist/home.conf");
        let up = up_argv(conf);
        assert!(up.last().unwrap().contains("home.conf"));
        // Without a config to point at, the interface name is what is left.
        assert!(down_argv(conf, "home").contains(&"home".to_string()));
    }
}
